### ISSUE TITLE
A feature to wrap the grid at edges

### ISSUE THREAD

**Issue by the-robo** [Sleavely/jquery-infinite-drag#4] opened 2015-12-09 05:55 UTC
A feature to wrap the grid at the edges would be great.  I am going to give this  a try, but don't have much time to focus on it.  Thought I would post an issue on the chance you may have time to look at this feature.  Thanks.

For example, a grid with a width and height of 100.  For brevity the below table is an example showing 1 tile in each direction, when viewed at x=0, y=0 

| 99,99 | 0,99 | 1,99 |
| --- | --- | --- |
| 99,0 | 0,0 | 1,0 |
| 99,01 | 0,1 | 1,1 |

**Comment by Sleavely** [comment] 2015-12-09 08:30
Just to clarify, you mean a grid that starts at the beginning when you reach the end?

**Comment by Sleavely** [comment] 2015-12-09 08:58
Have a look at #5 and let me know if it works as intended.

**Comment by the-robo** [comment] 2015-12-09 11:31
Wow, cool!  Thanks for the quick reply.  Yes, you could also describe it as, the grid will display 'the end' tiles adjacent to 'the beginning' tiles.  I tried the latest and didn't see any changes or new functionality.  I will double check to ensure I have the right one.

**Comment by the-robo** [comment] 2015-12-10 10:25
I double checked my file version and it is the latest.  Negative numbered tiles still show.

**Comment by the-robo** [comment] 2015-12-10 10:39
I thought of a work-around.  What if the tile appearance reflected the wrapping effect regardless of the underlying position.  I added this to my tile_options object:

``` javascript
    oncreate: function($element, col, row) {
        // wrap edges defined by bounds variable
        var bounds = 1000;
        var cntX = row, cntY = col;
        if(cntX >= (bounds * 2)) cntX = cntX % bounds; // if an order higher than bounds, reduce
        if(cntX >= bounds) cntX = cntX - bounds;       // if greater than bounds, reduce
        if(cntX < -(bounds)) cntX = cntX % bounds;       // if an order below bounds, increase
        if(cntX < 0) cntX = bounds + cntX;                       // if below bounds, raise
        if(cntY >= (bounds * 2)) cntY = cntY % bounds; // same for y 
        if(cntY >= bounds) cntY = cntY - bounds;
        if(cntY < -(bounds)) cntY = cntY % bounds;
        if(cntY < 0) cntY = bounds + cntY;
        $('<div class="_content" ' +
            'id="' + cntX + '.' + cntY + 
            '"x="' + cntX + 
            '"y="' + cntY + 
            '"></div>')
            .text(cntX + "." + cntY)
            .appendTo($element)
            .click(function(e) {
            clickTile($(this));
        });                 
    }
```

I will give it more rigorous testing when I have a bit more time.

**Comment by Sleavely** [comment] 2015-12-10 12:15
Sorry, I was speaking in Github lingo. What I mean was "check my proposed change here: https://github.com/Sleavely/jquery-infinite-drag/pull/5/files" :)

Anyway, glad you found a solution that works for you!

**Comment by the-robo** [comment] 2015-12-10 21:23
I would call my code a workaround.  What you proposed would be the more elegant solution.  One concern I have about my code is the potential for issues when a user drags in one direction to the extreme.  I am going to do some memory profiling and see if I can spot any problems.

**Comment by Sleavely** [comment] 2015-12-10 22:39
You should be fine as long as you have cleaning enabled. I think. :)

## 

On a related note in terms of performance, I think that instead of adding a separate event listener to each tile you'd stand to gain from binding a listener on the parent instead. Consider the following:

``` html
<div class="my-awesome-grid">
  <div class="tile">foo</div>
  <div class="tile">foo</div>
  <div class="tile">foo</div>
</div>
```

``` javascript
var $grid_thing = jQuery('.my-awesome-grid');
$grid_thing.on('click', '.tile', function(e){
  clickTile($(this));
});
```

The reason I suggest it is that it's possible you'll end up with loads of event listeners all being treated as separate variables that hog memory, plus you only have to define it once and it will automatically apply to any children that are dynamically added.

**Comment by the-robo** [comment] 2015-12-11 00:51
Great idea!  Then I just pull the "id" attribute and identify which tile was clicked.  Since I am going to have several layers and lots of other objects that need listeners this will help tremendously.  Thanks!

**Comment by Sleavely** [comment] 2015-12-11 09:17
No problem. I'm closing this issue for now but let me know if neither of the solutions work out.

**Closed as completed by Sleavely** 2015-12-11 09:17 UTC
